name: Python tests
on:
   pull_request:
     branches:
      - main
     paths:
      - 'src/**'
      - 'test/**'
      - 'setup.py'
      - 'Makefile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout package repository
      uses: actions/checkout@v3
      with:
        path: async-flow-control
    - name: Create venv
      run: |
        cd async-flow-control
        VENV="$GITHUB_WORKSPACE/venv" PYTHON_VERSION=${{ matrix.python-version }} make venv
    - name: Install package
      run: |
        cd async-flow-control
        VENV="$GITHUB_WORKSPACE/venv" make install
    - name: Test with pytest
      run: |
        cd async-flow-control
        VENV="$GITHUB_WORKSPACE/venv" make unit-verbose
